- name: copy elasticsearch repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install logstash
  ansible.builtin.dnf:
    name: logstash
    state: installed

- name: copy logstash config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: start logstash
  ansible.builtin.systemd_service:
    name: logstash
    state: started
    enabled: true
