- name: Get Secrets
  hosts: localhost
  vars:
    ssh: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.mohdshuja.com:8200 validate_certs=False')}}"
  tasks:
    - name: create file and add line
      ansible.builtin.lineinfile:
        path: /tmp/vault_secrets
        line: "Username: {{ ssh.ssh_user }}"
        create: yes
