- name: Get Secrets
  hosts: localhost
  tasks:
    - name: create file and add line
      ansible.builtin.lineinfile:
        path: /tmp
        line: "Username: {{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.mohdshuja.com:8200 validate_certs=False')}}"
        create: yes
