- name: Get Secrets
  hosts: localhost
  tasks:
    - name: create common secrets SSH file
      ansible.builtin.lineinfile:
        path: secrets.json
        line: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.mohdshuja.com:8200 validate_certs=False')}}"
        create: yes

- name: Get Secrets
  hosts: localhost
  tasks:
    - name: create App Secrets file
      ansible.builtin.lineinfile:
        path: app.json
        line: "{{lookup('hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.mohdshuja.com:8200 validate_certs=False')}}"
        create: yes