input {
  file {
    path => "{{log_file}}"
  }
}

output {
    elasticsearch {
        hosts => "https://elk-internal.mohdshuja.com:9200"
        user => "{{elasticsearch_user}}"
        password => "{{elasticsearch_password}}"
        ssl_verification_mode => "none"
         index => "frontend-%{+YYYY.MM.dd}"
    }
}
